### ISSUE TITLE
How to install django-adminlte-templates

### ISSUE THREAD

**Issue by NancyZY** [StephenPCG/django-adminlte-templates#6]
By reading the READ file, I cannot run success for my own project. it hints  "No module named AdminLTE". I tried using "pip install AdminLTE", but it doesn't work. Please tell me how to install it .Thanks in advance

**Comment by geghamjivanyan** [comment]
Try this 
pip install django-adminlte

**Comment by mervinkid** [comment]
This project have not been upload to `PyPI`. 
So you can not install this module with `pip` command.

Install this project with `setup.py` script:
1. Clone project to your disk.(`git clone https://github.com/StephenPCG/django-adminlte-templates`)
2. Make sure `python` and `django` have been installed.
3. Open your terminal application.
4. Change your working directory into `django-adminlte-templates`.
5. Run command `python setup.py install`.

Good luck.

**Comment by NancyZY** [comment]
@geghamjivanyan  still hint "No module named AdminLTE" with "python manage.py runserver", and I am sure django-adminlte already install , because it shows that:
![image](https://cloud.githubusercontent.com/assets/9473445/17847374/37f5be0c-6880-11e6-8eb5-d7f3ec143771.png)

**Comment by Diegow3b** [comment]
guys, dont install django-adminlte, u need to clone the project and run python setup.py install

**Comment by krism74** [comment]
Hi 
tying to run this and get some issues, here are the steps I have done

1. git clone the project
2. run setup : python setup.py install --> /django-adminlte-templates$ sudo python setup.py install
```
running install
running bdist_egg
running egg_info
creating django_adminlte_templates.egg-info
writing requirements to django_adminlte_templates.egg-info/requires.txt
writing django_adminlte_templates.egg-info/PKG-INFO
writing top-level names to django_adminlte_templates.egg-info/top_level.txt
writing dependency_links to django_adminlte_templates.egg-info/dependency_links.txt
writing manifest file 'django_adminlte_templates.egg-info/SOURCES.txt'
reading manifest file 'django_adminlte_templates.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'AdminLTE/static'
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.gitignore' found anywhere in distribution
writing manifest file 'django_adminlte_templates.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/AdminLTE
copying AdminLTE/context_processors.py -> build/lib.linux-x86_64-2.7/AdminLTE
copying AdminLTE/default_settings.py -> build/lib.linux-x86_64-2.7/AdminLTE
copying AdminLTE/__init__.py -> build/lib.linux-x86_64-2.7/AdminLTE
copying AdminLTE/settings.py -> build/lib.linux-x86_64-2.7/AdminLTE
creating build/lib.linux-x86_64-2.7/AdminLTE/templates
creating build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE
copying AdminLTE/templates/AdminLTE/base.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE
copying AdminLTE/templates/AdminLTE/login.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE
copying AdminLTE/templates/AdminLTE/page.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE
copying AdminLTE/templates/AdminLTE/register.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE
creating build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes
copying AdminLTE/templates/AdminLTE/includes/page_control_sidebar.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes
creating build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
copying AdminLTE/templates/AdminLTE/includes/page_header/control_sidebar.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
copying AdminLTE/templates/AdminLTE/includes/page_header/messages_dropdown.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
copying AdminLTE/templates/AdminLTE/includes/page_header/notifications_dropdown.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
copying AdminLTE/templates/AdminLTE/includes/page_header/tasks_dropdown.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
copying AdminLTE/templates/AdminLTE/includes/page_header/userprofile_dropdown.html -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header
creating build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/widgets
creating build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/widgets/sidebar
copying AdminLTE/templates/AdminLTE/widgets/sidebar/search_menu_items.js -> build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/widgets/sidebar
creating build/lib.linux-x86_64-2.7/AdminLTE/templatetags
copying AdminLTE/templatetags/AdminLTE.py -> build/lib.linux-x86_64-2.7/AdminLTE/templatetags
copying AdminLTE/templatetags/__init__.py -> build/lib.linux-x86_64-2.7/AdminLTE/templatetags
creating build/lib.linux-x86_64-2.7/AdminLTE/widgets
copying AdminLTE/widgets/__init__.py -> build/lib.linux-x86_64-2.7/AdminLTE/widgets
copying AdminLTE/widgets/sidebar.py -> build/lib.linux-x86_64-2.7/AdminLTE/widgets
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/AdminLTE
creating build/bdist.linux-x86_64/egg/AdminLTE/templatetags
copying build/lib.linux-x86_64-2.7/AdminLTE/templatetags/__init__.py -> build/bdist.linux-x86_64/egg/AdminLTE/templatetags
copying build/lib.linux-x86_64-2.7/AdminLTE/templatetags/AdminLTE.py -> build/bdist.linux-x86_64/egg/AdminLTE/templatetags
creating build/bdist.linux-x86_64/egg/AdminLTE/templates
creating build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/page.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/base.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/login.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE
creating build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/widgets
creating build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/widgets/sidebar
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/widgets/sidebar/search_menu_items.js -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/widgets/sidebar
creating build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes
creating build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header/messages_dropdown.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header/tasks_dropdown.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header/control_sidebar.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header/userprofile_dropdown.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_header/notifications_dropdown.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes/page_header
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/includes/page_control_sidebar.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE/includes
copying build/lib.linux-x86_64-2.7/AdminLTE/templates/AdminLTE/register.html -> build/bdist.linux-x86_64/egg/AdminLTE/templates/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/context_processors.py -> build/bdist.linux-x86_64/egg/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/default_settings.py -> build/bdist.linux-x86_64/egg/AdminLTE
creating build/bdist.linux-x86_64/egg/AdminLTE/widgets
copying build/lib.linux-x86_64-2.7/AdminLTE/widgets/sidebar.py -> build/bdist.linux-x86_64/egg/AdminLTE/widgets
copying build/lib.linux-x86_64-2.7/AdminLTE/widgets/__init__.py -> build/bdist.linux-x86_64/egg/AdminLTE/widgets
copying build/lib.linux-x86_64-2.7/AdminLTE/__init__.py -> build/bdist.linux-x86_64/egg/AdminLTE
copying build/lib.linux-x86_64-2.7/AdminLTE/settings.py -> build/bdist.linux-x86_64/egg/AdminLTE
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/templatetags/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/templatetags/AdminLTE.py to AdminLTE.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/context_processors.py to context_processors.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/default_settings.py to default_settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/widgets/sidebar.py to sidebar.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/widgets/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/AdminLTE/settings.py to settings.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying django_adminlte_templates.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_adminlte_templates.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_adminlte_templates.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_adminlte_templates.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying django_adminlte_templates.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/django_adminlte_templates-2.1.2.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing django_adminlte_templates-2.1.2.0-py2.7.egg
Copying django_adminlte_templates-2.1.2.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding django-adminlte-templates 2.1.2.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/django_adminlte_templates-2.1.2.0-py2.7.egg
Processing dependencies for django-adminlte-templates==2.1.2.0
Searching for Django==1.10.5
Best match: Django 1.10.5
Adding Django 1.10.5 to easy-install.pth file
Installing django-admin script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages

Finished processing dependencies for django-adminlte-templates==2.1.2.04. 
```

5. python manage.py runserver
```/django-adminlte-templates/example$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
```

6. run migrate
```
/django-adminlte-templates/example$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
```

7. run the server : python manage.py runserver

```
System check identified no issues (0 silenced).
January 19, 2017 - 15:19:47
Django version 1.10.5, using settings 'example.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 66, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: AdminLTE/page.html
[19/Jan/2017 15:19:52] "GET / HTTP/1.1" 500 85997
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 66, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 53, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: AdminLTE/page.html
```

please suggest if i am missing something here.

thanks
kris

**Comment by krism74** [comment]
Any comments on the issue reported?
